# Generated by Django 3.2.6 on 2021-08-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_pollingunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncedLgaResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(verbose_name='result_id')),
                ('lga_id', models.IntegerField(verbose_name='lga_id')),
                ('party_abbreviation', models.CharField(max_length=200, verbose_name='party_abbreviation')),
                ('party_score', models.IntegerField(verbose_name='party_score')),
                ('entered_by_user', models.CharField(max_length=200, verbose_name='entered_by_user')),
                ('date_entered', models.DateTimeField(verbose_name='date_entered')),
            ],
        ),
    ]
