# Generated by Django 3.2.6 on 2021-08-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_announcedlgaresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncedPollingUnitResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(verbose_name='unique_id')),
                ('polling_unit_uniqueid', models.IntegerField(verbose_name='lga_id')),
                ('party_abbreviation', models.CharField(max_length=200, verbose_name='party_abbreviation')),
                ('party_score', models.IntegerField(verbose_name='state_id')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncedStateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(verbose_name='result_id')),
                ('state_name', models.IntegerField(verbose_name='state_name')),
                ('party_abbreviation', models.CharField(max_length=200, verbose_name='party_abbreviation')),
                ('party_score', models.IntegerField(verbose_name='party_score')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncedWardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(verbose_name='result_id')),
                ('ward_name', models.IntegerField(verbose_name='ward_name')),
                ('party_abbreviation', models.CharField(max_length=200, verbose_name='party_abbreviation')),
                ('party_score', models.IntegerField(verbose_name='party_score')),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(verbose_name='unique_id')),
                ('lga_id', models.IntegerField(verbose_name='lga_id')),
                ('lga_name', models.CharField(max_length=200, verbose_name='lga_name')),
                ('state_id', models.IntegerField(verbose_name='state_id')),
                ('lga_description', models.TextField(blank=True, default='LGA description...', null=True, verbose_name='lga_description')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.CharField(max_length=200, verbose_name='party_name')),
                ('party_name', models.CharField(max_length=200, verbose_name='party_name')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField(verbose_name='state_id')),
                ('state_name', models.CharField(max_length=200, verbose_name='state_name')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(verbose_name='unique_id')),
                ('ward_id', models.IntegerField(verbose_name='ward_id')),
                ('ward_name', models.CharField(max_length=200, verbose_name='ward_name')),
                ('lga_id', models.IntegerField(verbose_name='lga_id')),
                ('ward_description', models.TextField(blank=True, default='Ward description...', null=True, verbose_name='ward_description')),
            ],
        ),
    ]
