# Generated by Django 3.2.6 on 2021-08-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_announcedpollingunitresult_announcedstateresult_announcedwardresult_lga_party_state_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcedpollingunitresult',
            name='party_score',
            field=models.IntegerField(verbose_name='party_score'),
        ),
        migrations.AlterField(
            model_name='announcedpollingunitresult',
            name='polling_unit_uniqueid',
            field=models.IntegerField(verbose_name='polling_unit_uniqueid'),
        ),
        migrations.AlterField(
            model_name='announcedpollingunitresult',
            name='result_id',
            field=models.IntegerField(verbose_name='result_id'),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_id',
            field=models.CharField(max_length=200, verbose_name='party_id'),
        ),
    ]
